### ISSUE TITLE
Retry connection

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#1]
Implements retry connections

**Comment by DBX12** [comment]
I think I can do this.

**Comment by marcus-campos** [comment]
Awesome! Thank you very much for contributing with the project. If you want, we can contact you through my email campos.v.marcus@gmail.com.

**Comment by marcus-campos** [comment]
@DBX12  and @tylfin Can we try together?

**Comment by DBX12** [comment]
I implement the retry feature using the Middleware class of Guzzle. This requires setting the config property `handler` in the Guzzle client. In the current `Rest::__construct()` you allow the derived class to supply a `$client` object. The two choices we have are either overwriting the `handler` property of the Client or removing the parameter `$client` from the constructor. What do you prefer?
