### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#17]
Add cache method option

**Comment by martinjoiner** [comment]
I can implement some caching using the PHP package APUc if you like? How long to you want to cache requests for by default? I could also make it configurable.

**Comment by marcus-campos** [comment]
Perfect, you can try to implement! I wish there was more than one way to set it up.

**Comment by martinjoiner** [comment]
I am trying to get it running inside a Laravel project so I can work on it but you've set requirements as minimum 7.1!  Is there really any code in there that is so new it will not run in PHP7?  I have managed to install it using the `--ignore-platform-reqs` flag but I would suggest lowering the minimum requirement.

**Comment by marcus-campos** [comment]
I agree with you. I will reduce the minimum requirements.

**Comment by marcus-campos** [comment]
Done.
