### ISSUE TITLE
Validation functions

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#23]
Validation functions @tylfin

**Comment by iwex** [comment]
What do you mean?

**Comment by marcus-campos** [comment]
I do not know if these functions would be necessary. I had been thinking of putting functions to validate whether the return is a json, html or xml.

**Comment by iwex** [comment]
But, you only json_decode)

**Comment by marcus-campos** [comment]
Yes, so I do not see any more need for these functions. I'll close this issue.
