### ISSUE TITLE
Integrate with Codecov

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#25]
Integrate the project with https://codecov.io/

**Comment by d3vil0p3r** [comment]
Working on this 👍

**Comment by rudr4x5h** [comment]
Working on this 👍

**Comment by rudr4x5h** [comment]
@marcus-campos need some more time learning this, phpunit throwing an error 
`Error:  No code coverage driver is available`
Do we need to install a driver like xDebug or similar here, because phpunit is not emitting any kind of coverage information, neither on STDIN nor writing to any file!

Need enlightenment.

**Comment by craig-davis** [comment]
@d3vil0p3r You most likely do not have `xdebug` installed. It is available on OSX via [Homebrew](https://brew.sh/). For example, you can use `brew install php70-xdebug` to install it if you are running PHP 7.0. (Note that it's not yet available via Brew for 7.2)

Brew /should/ update your ini file, but you may want to double check that it's available via `php -i | grep xdebug`.

**Comment by marcus-campos** [comment]
@d3vil0p3r Have you tried using docker? Have a Dockerfile in the project files, you could try installing xDebug and bind the port with your PC.

**Comment by rudr4x5h** [comment]
@craig-davis @marcus-campos Thank you sir for your support.
Actually everything is being run in a docker-ised environment. I'm using TravisCI, the error I mentioned earlier is displayed in the build logs of TravisCI.

I'll try installing xDebug via Dockerfile first and then will test building using TravisCI to see if that solves the issue.

**Comment by marcus-campos** [comment]
Okay. If you need help, call me on my email.
