### ISSUE TITLE
Fix: docker for local development and CI builds

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#26]
Attached is an image of the error that Travis has accused.

![captura de tela de 2017-10-18 21-08-17](https://user-images.githubusercontent.com/5151894/31746961-e338d78a-b448-11e7-97e1-31a24c6f5234.png)

@tylfin 

PR that caused the error #21

**Comment by tylfin** [comment]
@marcus-campos Should be fixed on master https://travis-ci.org/marcus-campos/maestro

**Comment by tylfin** [comment]
This commit fixed it https://github.com/marcus-campos/maestro/commit/68a8de3c44da84a0669c863dc951543f6a7fc301

**Comment by marcus-campos** [comment]
I had seen this commit, however, Travis was not letting pass the test. I added a few lines to install PHPUnit in Dockerfile
