### ISSUE TITLE
Laravel suport

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#32]
Create a provider and related for Laravel integration and support.

Ps: Put other Frameworks on the radar (Code Igniter, Symfony, Zend, etc.)

**Comment by owenvoke** [comment]
Not going to ask if I can claim this, but I may have a look. :+1:

**Comment by marcus-campos** [comment]
Claim it! Your contribution will be of great value to this project.

**Comment by pxgamer** [comment]
Just interested, is this more to add it as a facade for Laravel? As I can't really think of a reason for needing a provider.
