### ISSUE TITLE
Status request

### ISSUE THREAD

**Issue by marcus-campos** [marcus-campos/maestro#40]
Implement functions to capture HTTP / 1.1 codes according to RFC 2616 definitions

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by iwex** [comment]
And what do you man on this?
P.S. You have wrong json_decode usage. 
From docs:
```php
 public function postNotification()
 {
     return $this
         ->get()
         ->setEndPoint('package/')
         ->headers([
             'Content-Type' => 'application/json'
         ])
         ->body([
             'message' => 'Tanks for all.',
             'id' => [1]
         ])
         ->send()
         ->assoc()
         ->parse()
         ->name;
 }
```
But if you use assoc() => ```return json_decode($this->responseBody, true);``` will return array, not object, so you can't 
```php
->parse()
->name;
```

**Comment by marcus-campos** [comment]
About RFC, at this point the master is agnostic about any code that comes back from the server (if it returns 409 or 200, for it has no difference at all), and in some cases in development certain codes result in certain actions.

As for the documentation, it really is wrong. Can you pull a request to correct it?

**Comment by marcus-campos** [comment]
As for the code I imagined something like `->status()`

**Comment by iwex** [comment]
Okey

**Comment by iwex** [comment]
https://github.com/marcus-campos/maestro/pull/46 check pls)

**Comment by marcus-campos** [comment]
Perfect!
